#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'note_store_types'

      module Evernote
        module EDAM
          module NoteStore
    end
  end
end
