#
# Autogenerated by Thrift Compiler (0.5.0-en-exported)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'types_types'

module Evernote
  module EDAM
    module Type
      CLASSIFICATION_RECIPE_USER_NON_RECIPE = %q"000"

      CLASSIFICATION_RECIPE_USER_RECIPE = %q"001"

      CLASSIFICATION_RECIPE_SERVICE_RECIPE = %q"002"

      EDAM_NOTE_SOURCE_WEB_CLIP = %q"web.clip"

      EDAM_NOTE_SOURCE_WEB_CLIP_SIMPLIFIED = %q"Clearly"

      EDAM_NOTE_SOURCE_MAIL_CLIP = %q"mail.clip"

      EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = %q"mail.smtp"

    end
  end
end
