#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'types_types'

      module Evernote
        module EDAM
          module Type
            EDAM_NOTE_SOURCE_WEB_CLIP = %q"web.clip"

            EDAM_NOTE_SOURCE_MAIL_CLIP = %q"mail.clip"

            EDAM_NOTE_SOURCE_MAIL_SMTP_GATEWAY = %q"mail.smtp"

    end
  end
end
