#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'user_store_types'

      module Evernote
        module EDAM
          module UserStore
            EDAM_VERSION_MAJOR = 1

            EDAM_VERSION_MINOR = 21

    end
  end
end
