#
# Autogenerated by Thrift Compiler (0.5.0-en-exported)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'user_store_types'

module Evernote
  module EDAM
    module UserStore
      EDAM_VERSION_MAJOR = 1

      EDAM_VERSION_MINOR = 28

    end
  end
end
